include_guard(GLOBAL)

function(tx_print_build_info)
    message(STATUS "tx build configuration:")
    message(STATUS "  Version: ${PROJECT_VERSION}")
    message(STATUS "  Build type: ${CMAKE_BUILD_TYPE}")
    message(STATUS "  C compiler: ${CMAKE_C_COMPILER_ID} ${CMAKE_C_COMPILER_VERSION}")
    message(STATUS "  CXX compiler: ${CMAKE_CXX_COMPILER_ID} ${CMAKE_CXX_COMPILER_VERSION}")
    message(STATUS "  Build tests: ${TX_BUILD_TESTS}")
    message(STATUS "  Build shared: ${TX_BUILD_SHARED}")
    message(STATUS "  Fetch deps: ${TX_FETCH_DEPS}")
    message(STATUS "  Deps root: ${TX_DEPS_ROOT}")
    if(ANDROID)
        message(STATUS "  Android STL: ${ANDROID_STL}")
    endif()
endfunction()
